from typing import TypedDict
from typing import Dict, TypedDict, Annotated, Sequence
from langchain_core.messages import BaseMessage, SystemMessage, HumanMessage
from langgraph.graph.message import add_messages

class NanoCopilotState(TypedDict):
    target_file: str    # Path to the file we want to edit
    instructions: str   # What the user wants us to do
    file_content: str   # Raw content of the file (filled by code)
    proposed_edit: str  # Code block generated by the LLM
    status: str         # Track if we are "success" or "failed"

class AgentState(TypedDict):
    messages: Annotated[Sequence[BaseMessage], add_messages]